import type { Metadata } from "next";

import "./globals.css";
import { Roboto, Rubik } from "next/font/google";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });
const rubik = Rubik({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--title-font",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} ${rubik.variable}`}>
        {children}
      </body>
    </html>
  );
}
